name: "Proof Reader AI Action"
description: "Perform code reviews and comment on diffs on markdown article using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4o-mini"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  file-pattern:
    description: "Regex pattern to match files for review"
    required: false
    default: "\\.mdx$"
runs:
  using: "node20"
  main: "lib/main.js"
